blank_issues_enabled: false
contact_links:
  - name: "📚 Documentation"
    url: "https://github.com/xfreed0m/threatforge/blob/main/README.md"
    about: "Check our documentation for setup and usage information"
  - name: "💬 GitHub Discussions"
    url: "https://github.com/xfreed0m/threatforge/discussions"
    about: "Ask questions and discuss ideas with the community"
  - name: "🔒 Security Issues"
    url: "https://github.com/xfreed0m/threatforge/issues/new?assignees=&labels=security&template=&title=%5BSECURITY%5D+"
    about: "Report security vulnerabilities or concerns" 